version: '3'
services:
  client:
    image: "node:10-alpine"
    working_dir: /myapp/client
    volumes:
      - ./client:/myapp/client
    ports:
      - "3000:3000"
    command: "yarn start"
    depends_on:
      - backend
  db:
    image: postgres:9.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - db.env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3080 -b '0.0.0.0'; env"
    volumes:
      - .:/myapp
    ports:
      - "3080:3080"
    depends_on:
      - db
    env_file:
      - app.env
